# SPDX-License-Identifier: MIT
"""Generate site/tiers.js from config/tiers.json + palette.json.

The landing page never hand-copies a number: every price, range, luck value,
and zone color on the page comes from config through this script.

Usage:
    python scripts/build_site_data.py
"""
from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "engine"))

from shipgen.config import load_json, CONFIG_DIR  # noqa: E402

log = logging.getLogger("build_site_data")
ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    tiers = load_json(CONFIG_DIR / "tiers.json")
    palette = load_json(CONFIG_DIR / "palette.json")

    master = {c["name"]: c["hex"] for c in palette["master"]}
    zone_hex = {zone: [master[n] for n in names]
                for zone, names in palette["zones"].items()}

    rows = []
    for t in tiers["tiers"]:
        g = t["guarantee"] or {}
        if g.get("guaranteed_grail"):
            guarantee = "Guaranteed named Grail"
        elif g:
            guarantee = f"≥{g['count']} {g['min_tier'].capitalize()}"
            if g.get("grail_lottery"):
                guarantee += " + Grail lottery"
        else:
            guarantee = "—"
        chest = (str(t["chest_min"]) if t["chest_min"] == t["chest_max"]
                 else f"{t['chest_min']}–{t['chest_max']}")
        if t["name"] == "wizard_of_the_deep":
            chest = f"{t['chest_min']} + 1 Grail"
        rows.append({
            "name": t["display_name"],
            "zone": t["zone"],
            "price": t["price_xch"],
            "chest": chest,
            "expected": t["expected_mints"],
            "passes": t["passes"],
            "luck": (None if t["depth_luck"] is None else t["depth_luck"]),
            "guarantee": guarantee,
        })

    gs = tiers["grail_seeding"]
    data = {
        "supply": tiers["supply"]["cap"],
        "reserve": tiers["supply"]["treasury_reserve"],
        "grails": tiers["supply"]["grail_count"],
        "publicMintBudget": tiers["supply"]["public_mint_budget"],
        "generatedPool": tiers["supply"]["generated_pool"],
        "revenueFullSelloutXch": tiers.get("revenue_model_xch_full_sellout"),
        "grailSeeding": {
            "admiral": gs["admiral_chests"],
            "mid": gs["mid_tier_chests"],
            "auction": gs["auction"],
            "wizard": gs["wizard_of_the_deep"],
        },
        "rngAlgorithm": "HMAC-SHA256-DRBG-v1",
        "tiers": rows,
        "zoneColors": zone_hex,
    }
    out = ROOT / "site" / "tiers.js"
    out.write_text(
        "// GENERATED by scripts/build_site_data.py from config/tiers.json — do not edit\n"
        "const SHIP_DATA = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n",
        encoding="utf-8", newline="\n")
    log.info("wrote %s", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
